# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default:
    cmds:  
      - task: auth  
  auth:
    desc: "Start auth service"
    deps:
      - admins
    cmds:
      - go run ./cmd/auth --config=./config/dev.yaml

  test:
    desc: "Run auth servise (tests)"
    deps:
      - test-db
    cmds:
      - go run ./cmd/auth --config=./config/tests.yaml
  test-db:    
    cmds: 
      - go run ./cmd/migrator --storage-path=./storage/test.db --migrations-path=./migrations 
      - go run ./cmd/admins --storage=./storage/test.db --admins=./config/admins.yaml

  init_db:
    aliases:
      - db
    desc: "Initialize database"  
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/auth.db --migrations-path=./migrations      
  admins:
    desc: "Add admins to database"  
    deps:
      - init_db
    cmds:
      - go run ./cmd/admins --storage=./storage/auth.db --admins=./config/admins.yaml

  docker-build:
    aliases:
      - build
    cmds:
      - docker build -t auth:dev . 
  docker-run:
    aliases:
      - run
    cmds:
      - docker run -p 44044:44044 auth:dev 